In [3]:
%pip install -U pandas

Requirement already satisfied: pandas in c:\users\91628\anaconda3\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\91628\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91628\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\91628\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\91628\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

c:\Users\91628\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

**Series**

In [5]:
s = pd.Series([10,20,30,40,50], name="Marks") # name = Column name

In [6]:
print(type(s))

<class 'pandas.Series'>

In [7]:
print(s)

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64

In [8]:
print(s[0])
print(s.mean())

10
30.0

In [9]:
# Data Frame
data = {
  "Name":['Alice', 'Bob', 'Charle', "David", "Elvin", "Faf", "Grok", "Hazel", "Immanuel"],
  "Age":[24,27,22,32,37,47,27,67,57],
  "Score":[85,91,78,88,89,99,47,68,54]
}
df = pd.DataFrame(data)

In [10]:
print(type(df))

<class 'pandas.DataFrame'>

In [11]:
print(df)

       Name  Age  Score
0     Alice   24     85
1       Bob   27     91
2    Charle   22     78
3     David   32     88
4     Elvin   37     89
5       Faf   47     99
6      Grok   27     47
7     Hazel   67     68
8  Immanuel   57     54

In [12]:
df.head() #df.tail()

     Name  Age  Score
0   Alice   24     85
1     Bob   27     91
2  Charle   22     78
3   David   32     88
4   Elvin   37     89

In [13]:
# save the dataframe to a csv file
df.to_csv("data_sample.csv", index=False)

**Read data from a csv file**

In [14]:
ds = pd.read_csv("data_sample.csv")

In [15]:
ds.shape

(9, 3)

In [16]:
ds.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [17]:
ds.head() # first 5 rows in the dataframe

     Name  Age  Score
0   Alice   24     85
1     Bob   27     91
2  Charle   22     78
3   David   32     88
4   Elvin   37     89

In [18]:
ds.tail()

       Name  Age  Score
4     Elvin   37     89
5       Faf   47     99
6      Grok   27     47
7     Hazel   67     68
8  Immanuel   57     54

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str
 1   Age     9 non-null      int64
 2   Score   9 non-null      int64
dtypes: int64(2), str(1)
memory usage: 392.0 bytes

In [20]:
print("Shape:",ds.shape)
print("\nColumns:",ds.columns)
print("\nData types:\n", ds.dtypes)

Shape: (9, 3)

Columns: Index(['Name', 'Age', 'Score'], dtype='str')

Data types:
 Name       str
Age      int64
Score    int64
dtype: object

In [21]:
print(type(df["Name"]))

<class 'pandas.Series'>

In [22]:
print(df[["Name", "Age"]])

       Name  Age
0     Alice   24
1       Bob   27
2    Charle   22
3     David   32
4     Elvin   37
5       Faf   47
6      Grok   27
7     Hazel   67
8  Immanuel   57

In [23]:
print(type(df[["Name", "Age"]]))

<class 'pandas.DataFrame'>

In [24]:
# Row Selection
print(df.iloc[0]) # by index

Name     Alice
Age         24
Score       85
Name: 0, dtype: object

In [25]:
print(df.loc[0])

Name     Alice
Age         24
Score       85
Name: 0, dtype: object

In [26]:
print(df.loc[1])

Name     Bob
Age       27
Score     91
Name: 1, dtype: object

In [27]:
data = {
  "Name":["Raghava", "Ramana", "Rama", "Krishna"],
  "Score":[88,92,95,78]
}

sample_data_2 = pd.DataFrame(data, index=["a", "b", "c", "d"])

In [28]:
sample_data_2.head()

      Name  Score
a  Raghava     88
b   Ramana     92
c     Rama     95
d  Krishna     78

In [29]:
sample_data_2.iloc[1] # to print based on the position

Name     Ramana
Score        92
Name: b, dtype: object

In [30]:
sample_data_2.loc["b"] # when you have the custom label then use loc if you wanna print with labels

Name     Ramana
Score        92
Name: b, dtype: object

*Filtering rows with Condition*

In [31]:
# filter the rows whose marks is less than or equal to 50

print(df[df["Score"] <= 85])

       Name  Age  Score
0     Alice   24     85
2    Charle   22     78
6      Grok   27     47
7     Hazel   67     68
8  Immanuel   57     54

In [32]:
# Creating the new Columns in the Dataset

df["Passed"] = df["Score"] >= 60

In [33]:
df

       Name  Age  Score  Passed
0     Alice   24     85    True
1       Bob   27     91    True
2    Charle   22     78    True
3     David   32     88    True
4     Elvin   37     89    True
5       Faf   47     99    True
6      Grok   27     47   False
7     Hazel   67     68    True
8  Immanuel   57     54   False

In [34]:
df['Score_Percentage'] = (df['Score'] / 100) * 100

In [35]:
df

       Name  Age  Score  Passed  Score_Percentage
0     Alice   24     85    True              85.0
1       Bob   27     91    True              91.0
2    Charle   22     78    True              78.0
3     David   32     88    True              88.0
4     Elvin   37     89    True              89.0
5       Faf   47     99    True              99.0
6      Grok   27     47   False              47.0
7     Hazel   67     68    True              68.0
8  Immanuel   57     54   False              54.0

In [37]:
# To add completely new Column
df['city'] = ['Delhi', 'Mumbai', 'Hyderabad', 'Bangalore', 'Chennai', 'Kolkata',None, None, None]

In [38]:
df

       Name  Age  Score  Passed  Score_Percentage       city
0     Alice   24     85    True              85.0      Delhi
1       Bob   27     91    True              91.0     Mumbai
2    Charle   22     78    True              78.0  Hyderabad
3     David   32     88    True              88.0  Bangalore
4     Elvin   37     89    True              89.0    Chennai
5       Faf   47     99    True              99.0    Kolkata
6      Grok   27     47   False              47.0        NaN
7     Hazel   67     68    True              68.0        NaN
8  Immanuel   57     54   False              54.0        NaN

**Descriptive Statistics**

In [39]:
print("Average Score:", df['Score'].mean())
print("Maximum Score:", df['Score'].max())
print("Minimum Score:", df['Score'].min())

Average Score: 77.66666666666667
Maximum Score: 99
Minimum Score: 47

In [40]:
df.describe()

             Age      Score  Score_Percentage
count   9.000000   9.000000          9.000000
mean   37.777778  77.666667         77.666667
std    15.864881  17.734148         17.734148
min    22.000000  47.000000         47.000000
25%    27.000000  68.000000         68.000000
50%    32.000000  85.000000         85.000000
75%    47.000000  89.000000         89.000000
max    67.000000  99.000000         99.000000

*To Update the Value*

In [43]:
sample_data_3 = pd.DataFrame(data)

In [47]:
df

       Name  Age  Score  Passed  Score_Percentage       city
0     Alice   24     85    True              85.0      Delhi
1       Bob   27     91    True              91.0     Mumbai
2    Charle   22     78    True              78.0  Hyderabad
3     David   32     88    True              88.0  Bangalore
4     Elvin   37     89    True              89.0    Chennai
5       Faf   47     99    True              99.0    Kolkata
6      Grok   27     47   False              47.0        NaN
7     Hazel   67     68    True              68.0        NaN
8  Immanuel   57     54   False              54.0        NaN

In [49]:
df.loc[df['Name'] == 'Elvin', 'Name'] = 'Erick'

In [50]:
df

       Name  Age  Score  Passed  Score_Percentage       city
0     Alice   24     85    True              85.0      Delhi
1       Bob   27     91    True              91.0     Mumbai
2    Charle   22     78    True              78.0  Hyderabad
3     David   32     88    True              88.0  Bangalore
4     Erick   37     89    True              89.0    Chennai
5       Faf   47     99    True              99.0    Kolkata
6      Grok   27     47   False              47.0        NaN
7     Hazel   67     68    True              68.0        NaN
8  Immanuel   57     54   False              54.0        NaN

In [55]:
df.loc[df['Score'] > 90, 'Score'] = None
df

       Name  Age  Score  Passed  Score_Percentage       city
0     Alice   24   85.0    True              85.0      Delhi
1       Bob   27    NaN    True              91.0     Mumbai
2    Charle   22   78.0    True              78.0  Hyderabad
3     David   32   88.0    True              88.0  Bangalore
4     Erick   37   89.0    True              89.0    Chennai
5       Faf   47    NaN    True              99.0    Kolkata
6      Grok   27    NaN   False              47.0        NaN
7     Hazel   67   68.0    True              68.0        NaN
8  Immanuel   57    NaN   False              54.0        NaN

*Handling Missing Data*

In [57]:
df.loc[df['Score'] == None, 'Score'] = 0
df.loc[df['Name'] == 'Erick', 'Name'] = None
df

       Name  Age  Score  Passed  Score_Percentage       city
0     Alice   24   85.0    True              85.0      Delhi
1       Bob   27    NaN    True              91.0     Mumbai
2    Charle   22   78.0    True              78.0  Hyderabad
3     David   32   88.0    True              88.0  Bangalore
4       NaN   37   89.0    True              89.0    Chennai
5       Faf   47    NaN    True              99.0    Kolkata
6      Grok   27    NaN   False              47.0        NaN
7     Hazel   67   68.0    True              68.0        NaN
8  Immanuel   57    NaN   False              54.0        NaN

In [58]:
df.head()

     Name  Age  Score  Passed  Score_Percentage       city
0   Alice   24   85.0    True              85.0      Delhi
1     Bob   27    NaN    True              91.0     Mumbai
2  Charle   22   78.0    True              78.0  Hyderabad
3   David   32   88.0    True              88.0  Bangalore
4     NaN   37   89.0    True              89.0    Chennai

In [ ]:
df.dropna(subset=['Name'], inplace=True, ignore_index=True) #ignore_index = True :-- it resets the index

In [63]:
df

       Name  Age  Score  Passed  Score_Percentage       city
0     Alice   24   85.0    True              85.0      Delhi
1       Bob   27    NaN    True              91.0     Mumbai
2    Charle   22   78.0    True              78.0  Hyderabad
3     David   32   88.0    True              88.0  Bangalore
4       Faf   47    NaN    True              99.0    Kolkata
5      Grok   27    NaN   False              47.0        NaN
6     Hazel   67   68.0    True              68.0        NaN
7  Immanuel   57    NaN   False              54.0        NaN

In [64]:
df['Score'] = df['Score'].fillna(df['Score'].mean())